extends:
  - eslint:recommended
  - plugin:eslint-comments/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:jsdoc/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: ./tsconfig.lint.json
  allowAutomaticSingleRunInference: true
plugins:
  - '@typescript-eslint'
  - filenames
  - jsdoc
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
root: true
reportUnusedDisableDirectives: true
rules:
  '@typescript-eslint/ban-ts-comment':
    - error
    - ts-expect-error: allow-with-description
      ts-ignore: true
      ts-nocheck: true
  '@typescript-eslint/consistent-type-assertions': error
  '@typescript-eslint/consistent-type-definitions': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/explicit-member-accessibility':
    - error
    - accessibility: no-public
  '@typescript-eslint/method-signature-style': error
  '@typescript-eslint/no-base-to-string': error
  '@typescript-eslint/no-confusing-non-null-assertion': error
  '@typescript-eslint/no-dynamic-delete': error
  '@typescript-eslint/no-extra-semi': error
  '@typescript-eslint/no-extraneous-class': error
  '@typescript-eslint/no-implicit-any-catch': error
  '@typescript-eslint/no-invalid-void-type': error
  '@typescript-eslint/no-require-imports': error
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': error
  '@typescript-eslint/no-unnecessary-qualifier': error
  '@typescript-eslint/no-unnecessary-type-arguments': error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  '@typescript-eslint/prefer-enum-initializers': error
  '@typescript-eslint/prefer-for-of': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/prefer-literal-enum-member': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/require-array-sort-compare': error
  '@typescript-eslint/switch-exhaustiveness-check': error
  '@typescript-eslint/unified-signatures': error
  'eslint-comments/no-unused-disable': 'error'
  'filenames/match-regex':
    - 'error'
    - '^[a-z0-9-.]+$' # Kebab-case.
  jsdoc/check-param-names: off
  jsdoc/newline-after-description: off
  jsdoc/require-jsdoc:
    - error
    - publicOnly: true
  jsdoc/require-returns: off
  jsdoc/require-returns-type: off
  jsdoc/require-param: off
  jsdoc/require-param-type: off
  jsdoc/tag-lines: off
overrides:
  - files: tests/**/*.test.{js,ts}
    plugins:
      - vitest
    rules:
      'vitest/lower-case-title': error
      'vitest/no-focused-tests': error
      'vitest/no-identical-title': error
      'vitest/no-skipped-tests': error
